In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('H:\\dataset\\winequality_red.csv')

In [3]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
X = dataset.iloc[:,0:13].values
y = dataset.iloc[:,-1].values

In [5]:
X,y

(array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
        [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
        [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
        ...,
        [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
        [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
        [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]]),
 array([5, 5, 5, ..., 6, 5, 6], dtype=int64))

In [6]:
X.shape, y.shape

((1599, 12), (1599,))

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state= 0)

In [8]:
X_train.shape, X_test.shape


((1279, 12), (320, 12))

In [9]:
y_train.shape, y_test.shape

((1279,), (320,))

In [10]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

In [11]:
X_train.shape, X_test.shape

((1279, 12), (320, 12))

In [12]:
X_train, X_test

(array([[ 0.90103398,  0.05480282,  0.9094138 , ..., -0.22358408,
         -0.95579434, -0.78933274],
        [ 1.41998736, -1.47967601,  0.9094138 , ..., -0.68130963,
         -0.76727388, -0.78933274],
        [ 0.90103398, -0.98645067,  1.4208416 , ...,  0.74908272,
          0.17532846, -0.78933274],
        ...,
        [-0.25219574,  0.21921126,  0.19341488, ...,  0.17692578,
         -0.86153411,  0.43141282],
        [ 2.68854005, -0.32881689,  1.11398492, ...,  0.11971008,
          2.15479335,  0.43141282],
        [ 0.84337249,  2.46612668,  0.24455766, ..., -1.0246038 ,
         -0.95579434, -0.78933274]]),
 array([[ 1.44653617, -0.29922497,  0.8557103 , ...,  0.72205872,
          0.31519731,  0.53693343],
        [-0.08433993,  1.83333604, -1.39006001, ..., -0.85116573,
         -0.79369656, -0.78474886],
        [ 0.48265122, -1.39597062,  0.33343814, ...,  1.26926723,
          1.14686771,  1.85861572],
        ...,
        [ 0.48265122, -1.09131905,  0.80348308, ..., -

In [13]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [14]:
lda = LDA(n_components = 2)

X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)


In [15]:
X_train, X_test

(array([[-1.88842441e+14],
        [-1.88842441e+14],
        [-1.88842441e+14],
        ...,
        [ 1.03212555e+14],
        [ 1.03212555e+14],
        [-1.88842441e+14]]),
 array([[ 1.28457638e+14],
        [-1.87745779e+14],
        [ 4.44661056e+14],
        [ 1.28457638e+14],
        [-1.87745779e+14],
        [ 1.28457638e+14],
        [-1.87745779e+14],
        [ 1.28457638e+14],
        [-5.03949197e+14],
        [-1.87745779e+14],
        [-1.87745779e+14],
        [-1.87745779e+14],
        [ 1.28457638e+14],
        [-1.87745779e+14],
        [ 1.28457638e+14],
        [ 1.28457638e+14],
        [ 4.44661056e+14],
        [-1.87745779e+14],
        [-1.87745779e+14],
        [-5.03949197e+14],
        [ 4.44661056e+14],
        [ 1.28457638e+14],
        [ 1.28457638e+14],
        [-5.03949197e+14],
        [ 1.28457638e+14],
        [-1.87745779e+14],
        [-1.87745779e+14],
        [ 4.44661056e+14],
        [-1.87745779e+14],
        [ 1.28457638e+14],
        [-1.8

In [16]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\suwarna\Anaconda3\envs\pytorch\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=0)

In [17]:
y_pred = classifier.predict(X_test)


y_pred

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [18]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

cm


array([[  2,   0,   0,   0,   0,   0],
       [ 11,   0,   0,   0,   0,   0],
       [135,   0,   0,   0,   0,   0],
       [142,   0,   0,   0,   0,   0],
       [ 27,   0,   0,   0,   0,   0],
       [  3,   0,   0,   0,   0,   0]], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(accuracy*100)

0.625
